apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cronofy-secrets
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
type: Opaque
data:
  CRONOFY_CLIENT_ID: {{ .Values.cronofySecrets.clientId | b64enc }}
  CRONOFY_CLIENT_SECRET: {{ .Values.cronofySecrets.clientSecret | b64enc }}